stages:
  - build

build-images:
  stage: build
  image: jdrouet/docker-with-buildx:latest
  services:
    - docker:dind
  parallel:
    matrix:
      - PROJECT_FOLDER:
        - docker-with-buildx
        - docker-with-compose
        - node-mjml
        - rust-clippy
        - rust-rustfmt
  before_script:
    - apk add --no-cache bash curl jq
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
    - docker buildx create --use --platform linux/amd64,linux/arm64
  script:
    - cd $PROJECT_FOLDER && EXTRA_ARGS="--push" bash ./build.sh

